### ISSUE TITLE
Sometimes, GetMemoryBlock returns NULL

### ISSUE THREAD

**Issue by RaMMicHaeL** [TsudaKageyu/minhook#10]
I got a bug report from a user, and after some investigation, it turned out that the [`GetMemoryBlock`](https://github.com/TsudaKageyu/minhook/blob/978e8c7f706f2c519bbd01d5d5d94fdb77a9815a/src/buffer.c#L88) function returns `NULL` for one of the functions on his machine. That means that MinHook could not find a memory block near the origin function (± 16MB).

Before I dive to the code and try to implement a solution, I have a couple of questions:
* Why is `MAX_MEMORY_RANGE` defined as `0x02000000`? Why not something along the lines of `0x80000000`, which is the range of the long jump?
* Why is [the scan for a new block](https://github.com/TsudaKageyu/minhook/blob/978e8c7f706f2c519bbd01d5d5d94fdb77a9815a/src/buffer.c#L120) implemented this way? Why scan for every 0x1000-th address instead of using `VirtualQuery`? Why is 0x1000 hardcoded, isn't it more correct to use the system allocation granularity?

P.S. another thing that I've stumbled upon and I want to ask: does the 64-bit relay have a purpose, or is it a historical leftover? As far as I see, just the trampoline can be used instead, but perhaps I'm missing something.

**Comment by TsudaKageyu** [comment]
> Why is MAX_MEMORY_RANGE defined as 0x02000000? Why not something along the lines of 0x80000000, which is the range of the long jump?

Sorry, this should be fixed immediately. 
I decreased the value to avoid an excessively long loop. I decided the value according to my experiment, but now it's clear that we should return it back. The original value ```0x20000000``` has to be enough. 
However, I can't fix it right now. If you have a dire need, please fix it on your side and create a pull request.

> Why scan for every 0x1000-th address instead of using ```VirtualQuery```?

If using ```VirtualQuery``` before ```VirtualAlloc```, another thread can interrupt and allocate the same address. (It's very unlikely, but possible.) 

>Why is 0x1000 hardcoded

The 64K granularity hasn't been changed for a long time. Raymond Chen described the reason: http://blogs.msdn.com/b/oldnewthing/archive/2003/10/08/55239.aspx
However, you are right that it's more well-behaved to check the actual granularity.

> does the 64-bit relay have a purpose

It's essential to MinHook to be able to work in x64 environment. A relay function serves as a relay point between 32-bit and 64-bit jump. If we overwrite a function with a 64-bit jump, it will take up at least 14 bytes. So we have no choice but overwrite 32-bit jump there. And this is why we should allocate the memory block in the vicinity of the target function.

**Comment by RaMMicHaeL** [comment]
Pull request: https://github.com/TsudaKageyu/minhook/pull/12

I'm not an expert in all the details of Windows virtual memory management, so please take a look before merging. It seems to work, but I didn't do extensive testing.

> If using VirtualQuery before VirtualAlloc, another thread can interrupt and allocate the same address. (It's very unlikely, but possible.)

If that happens, I just continue with the search.

**Comment by TsudaKageyu** [comment]
Thanks for #12.

> If that happens, I just continue with the search.

Privately, I think that if we check again after ```VirtualAlloc```, we don't need to use ```VirtualQuery``` beforehand. I guess ```VirtualAlloc``` does the same check as ```VirtualQuery``` internally.

**Comment by RaMMicHaeL** [comment]
Are you suggesting that `VirtualQuery` is redundant? I use it to iterate in large blocks while possible. e.g. if a 4MB chunk of memory is allocated, I can skip it altogether instead of checking every `0x1000` bytes.

**Comment by TsudaKageyu** [comment]
Oh! I see. It slipped my mind that ```MEMORY_BLOCK_SIZE``` is no longer necessarily equal to the allocation granularity. Thanks!
