### ISSUE TITLE
MinHook seems to be failing to read the instructions properly

### ISSUE THREAD

**Issue by ThePixelGamer** [TsudaKageyu/minhook#108]
Hi I'm trying to hook this one function that looks like this
![image](https://user-images.githubusercontent.com/15077848/211976834-ddf3ee4a-edf8-4690-b289-fb0a306e33b9.png)
but for some reason MinHook is failing to understand that the instruction at C4 is 2 bytes long which results in this
![image](https://user-images.githubusercontent.com/15077848/211976919-a53702c4-d015-45d3-b02e-98dc1feb3d88.png)
Something to note I'm currently using the latest GitHub release and haven't tried using a build of master yet, if this is a duplicate feel free to close.

**Comment by m417z** [comment]
There's nothing wrong in this picture. MinHook is supposed to jump back to C6 when the original function is called through the pointer it returns. The byte at C5 (54 - `push rsp`) will just never be used. MinHook could patch is with a nop, but that's just extra work that can be avoided.

**Comment by m417z** [comment]
There's nothing wrong in this picture. MinHook is supposed to jump back to C6 when the original function is called through the pointer it returns. The byte at C5 (54 - `push rsp`) will just never be used. MinHook could patch it with a nop, but that's just extra work that can be avoided.

**Comment by ThePixelGamer** [comment]
Ah I see, I guess I should've examined the trampoline before posting this. Thanks for the clarification!
