### ISSUE TITLE
Hooking function fails due to FindPrevFreeRegion and FindNextFreeRegion returning null

### ISSUE THREAD

**Issue by g0dzcsgo** [TsudaKageyu/minhook#110]
As the title says, hooking fails due to the FindPrevFreeRegion and FindNextFreeRegion returning null inside of the GetMemoryBlock function. The thing is I can hook something else just fine from the same class, but this does not hook. Any idea why these 2 functions would fail? And it's a valid origin function pointer I am passing.

**Comment by m417z** [comment]
See the discussion at https://github.com/TsudaKageyu/minhook/issues/107

**Comment by g0dzcsgo** [comment]
> See the discussion at #107

I don't know how to make these changes, e.g the change to absolute jumps instead of relative?

**Comment by m417z** [comment]
I'm closing the issue in favor of https://github.com/TsudaKageyu/minhook/issues/107
Meanwhile you might want to try this fork: https://github.com/EthanZoneCoding/minhook
