### ISSUE TITLE
how to use minhook without minhook's dll

### ISSUE THREAD

**Issue by INKCR0W** [TsudaKageyu/minhook#133]
I used MinHook in my DLL. When I injected my DLL into the target process, I found that MinHook.X64.dll was also loaded. How can I use MinHook without MinHook.X64.dll?

**Comment by Aetopia** [comment]
Try statically linking it to your binary.

**Comment by INKCR0W** [comment]
> Try statically linking it to your binary.

Thanks for response

But how to do it?
I tried linking MinHook.x64.lib to my project and loaded it in the code, but the DLL was still loaded when I ran my program

**Comment by INKCR0W** [comment]
nwm, it's my fault, I linked the wrong lib
thanks for your help
