### ISSUE TITLE
__try/__finally can cause a deadlock in x64 mode.

### ISSUE THREAD

**Issue by Aleh-Kazakevich** [TsudaKageyu/minhook#14]
Hi ! I found a bug in MinHook (hook.c).

Problem

    In x64 mode, the __try/__finally blocks between the Freeze() and Unfreeze() calls
    can cause a deadlock if other thread was frozen inside the LoadLibrary or FreeLibrary.
    
Description

    Internally, x64 stack unwinding (RtlUnwindEx -> RtlLookupFunctionTable) and
    loading/unloading a dll (LdrLoadDll/LdrUnloadDll) are using the same synchronization
    lock in the ntdll.dll (RTL_SRWLOCK ntdll!LdrpInvertedFunctionTable). If the thread
    was frozen while holding the lock then no other thread can perform stack unwinding
    or load/unload dll. This cause a deadlock.

 Example call stacks
    
    Thread-1 (main):
    
        nt!KiSwapContext+0x7a
        nt!KiCommitThreadWait+0x1d2
        nt!KeWaitForSingleObject+0x19f
        nt!NtWaitForKeyedEvent+0x15a
        nt!KiSystemServiceCopyEnd+0x13
        ntdll!NtWaitForKeyedEvent+0xa           3. Try to acquire lock = DEADLOCK !
        ntdll! ?? ::FNODOBFM::`string'+0x95b7
        ntdll!RtlLookupFunctionTable+0x3b
        ntdll!RtlLookupFunctionEntry+0x31
        ntdll!RtlUnwindEx+0xd7
        kernel32!RtlUnwindExStub+0x1e
        MinHookDeadlock!_local_unwind+0x1c      2. Begin unwinding the stack.
        MinHookDeadlock!EnableHook+0x144        1. Setting the hook (see hook.c, line 664).
        MinHookDeadlock!main+0xa3
        MinHookDeadlock!__tmainCRTStartup+0x144
        kernel32!BaseThreadInitThunk+0xd
        ntdll!RtlUserThreadStart+0x1d
        
    Thread-2 (worker):
    
        nt!KiSwapContext+0x7a
        nt!KiCommitThreadWait+0x1d2
        nt!KeWaitForSingleObject+0x19f
        nt!KiSuspendThread+0x54                     3. Somebody was called Freeze().
        nt!KiDeliverApc+0x201
        nt!KiApcInterrupt+0xd7
        ntdll!RtlAcquireSRWLockExclusive+0x19       2. Acquiring the lock.
        ntdll!RtlInsertInvertedFunctionTable+0x20
        ntdll!LdrpFindOrMapDll+0x738
        ntdll!LdrpLoadDll+0x148
        ntdll!LdrLoadDll+0x9a
        KERNELBASE!LoadLibraryExW+0x19c             1. Loading the dll.
        MinHookDeadlock!ThreadProc+0x1d
        MinHookDeadlock!_callthreadstartex+0x17
        MinHookDeadlock!_threadstartex+0x102
        kernel32!BaseThreadInitThunk+0xd
        ntdll!RtlUserThreadStart+0x1d

Example

    I have an example source code and compiled exe (VS2013 update 4,
    tested on Windows 7 64-bit):

    https://drive.google.com/file/d/0B3wmqwvKYtEUYm5UbkRjencydmc/view?usp=sharing

    Note that is not easy to reproduce this bug and you may need much time.
    
Solution

    Remove all __try/__finally blocks from hook.c.

**Comment by TsudaKageyu** [comment]
Hi @Aleh-Kazakevich, thanks for your kind report. 
I just received your example. I'm going to investigate it soon.

**Comment by TsudaKageyu** [comment]
I could easily reproduce it. Thanks again for finding such a subtle bug.

Removing ```__try/__finally``` requires a lot of tests because missing to call ```LeaveSpinLock()``` leads to another bug. So it will take some time to fix it.
