### ISSUE TITLE
VS12 libMinHook project always rebuilds

### ISSUE THREAD

**Issue by tapcio** [TsudaKageyu/minhook#18]
Take me awhile to debug why libMinHook project always rebuilds  -extreme painful when you run debug. Root cause is VS2013 stupidity - when you set `Debug Information Format` to `None` then PDB file is not created in output directory, and it cause missing output ... :

    32	1635.171124	6864	devenv.exe	CPS Verbose: 0 :
    33	1635.171182	6864	devenv.exe	Project 'E:\SourceTree\x360ce\MinHook\build\VC12\libMinHook.vcxproj' not up to date because 1 build outputs were missing.
    34	1635.171250	6864	devenv.exe	CPS Verbose: 0 :
    35	1635.171285	6864	devenv.exe	up to date is missing: 'E:\SOURCETREE\X360CE\MINHOOK\BUILD\VC12\WIN32\RELEASE\LIBMINHOOK\VC120.PDB'

Solution is to delete `Program Database File Name` in `Output Files` (which is set to default value of `"$(IntDir)vc$(PlatformToolsetVersion).pdb"`) or change `Debug Information Format`.

**Comment by TsudaKageyu** [comment]
Hi, sorry for being late.
This doesn't reproduce on my side. Possibly, it may depend on the minor version of Visual Studio.
The version info of my VS is like:
```Microsoft Visual Studio Community 2013 Version 12.0.31101.00 Update 4```

**Comment by tapcio** [comment]
I use Community as well. I think I do a clear install of W10 after its premiere so I reinstall VS2013 and recheck this. But this issue was happing to me from a long time.

**Comment by TsudaKageyu** [comment]
I see. Please give me some time to check it. Thanks.

**Comment by TsudaKageyu** [comment]
Visual Studio Community 2013 Update 5 was released a few days ago. [blogs.msdn.com](http://blogs.msdn.com/b/visualstudio/archive/2015/07/20/visual-studio-2015-and-visual-studio-2013-update-5-released.aspx)
Can you try it?

**Comment by star114** [comment]
I also have same problem using Visual Studio 2013 Premium update 5.
If I change Debug Information Format to Program Database(/Zi), It works well.

Visual Studio 2010 Professional(VC10) in same environment has no problems.

**Comment by tapcio** [comment]
Sorry for delay, but I forgot about this issue ... I upgraded (clean install) my PC to Windows 10 Pro and installed Visual Studio Community 2013 Update 5 from iso. Problem persisted - VS2013 always rebuild project when `Debug Information Format` is `None`. This not only affect minhook but all project, it seems to be bug in MSBUILD.

**Comment by Helios-vmg** [comment]
Hey, I just came across this thread while researching this problem in my own project, I thought I would share what I learned, in case you're still having problems with this.
I managed get this to work by:
1. Under Project Properties > Configuration Properties > Linker > Debugging, set the Generate Debug Info flag to No and set the Generate Program Database File field to "$(OutDir)$(TargetName).pdb".
2. Under Project Properties > Configuration Properties > C/C++ > Output Files, set the Program Database File Name field to "$(OutDir)$(TargetName).pdb". By default, this is set to "$(IntDir)vc$(PlatformToolsetVersion).pdb", for some reason. It appears this should be set to same value as the other field for the build process to behave correctly.

Hope this helps.

**Comment by TsudaKageyu** [comment]
Hi Víctor, thanks for your report.
I'm going to release the next version tomorrow, so I have no time to thoroughly test your method before I will release it.
I will check it after v1.3 will be released.

**Comment by Helios-vmg** [comment]
Correction: "Generate Debug Info" should be set to "Yes" if the other fields are set to anything other than an empty string.

**Comment by star114** [comment]
@Helios-vmg Thank you for your advice.
