### ISSUE TITLE
automatically hook functions when dlls load

### ISSUE THREAD

**Issue by star114** [TsudaKageyu/minhook#21]
hello,

Now, MH_CreateHookApi  cannot support this role. If GetModuleHandleW returns NULL, MH_CreateHookApi also returns MH_ERROR_MODULE_NOT_FOUND error.

when dlls load, I want to hook automatically detour functions already registered.

Do you have a plan to support this?

**Comment by TsudaKageyu** [comment]
A similar feature was suggested at #9, but I removed it at 4c129d6bc74976e54c0e67c1af3ae28d1cf4d5bf.

We need to actually load a DLL to create a hook, since we need to know the address of the function. (And #9 did it.) However, we have no opportunities to free the DLL properly, or we cannot know when we should free it.

**Comment by star114** [comment]
It's different between my suggestion and #9.

1. Hook "LoadLibrary" Function internally.
2. If program load dlls, it must enter detoured "LoadLibrary" function (my own function.)
3. In detoured "LoadLibrary" function, we can compare parameters with registered dll names and function names.
4. If it matchs each other, call MH_CreateHookApi.

I think it is possible, isn't it?


Is it

**Comment by TsudaKageyu** [comment]
I see your point. Yes, it is possible, but should it be done in user-side code? 
I am a frequent user of MinHook as well as being the creator. If I need a such feature as a user, it will be safer and more flexible to implement it in user-side code, not inside MinHook.

Additionally, as the name "MinHook" describes itself, we emphasize the importance of being minimalist. And I don't think this feature benefits a lot of users.

**Comment by star114** [comment]
You're right. 
It should be done in user-side code, too.
I thought that many poeple need this feature before.
If you don't agree this, I will implement it in my user-side code.
Thank you! :D
