### ISSUE TITLE
MinGW build generates wrong code

### ISSUE THREAD

**Issue by martinbbjerregaard** [TsudaKageyu/minhook#22]
Due to the usage of bitfields in the HOOK_ENTRY struct (hook.c), the -funsigned-bitfields flag need to be passed to the gcc compiler. If this flag is not passed, the generated code is wrong.

To fix the issue, change the line in the MinGW makefile:
CFLAGS:=-masm=intel -Wall -Werror -std=c11
to
CFLAGS:=-masm=intel -Wall -Werror -std=c11 -funsigned-bitfields

EDIT:
and of course the flag needs to be added to the make.bat file as well, I forgot about that.

**Comment by TsudaKageyu** [comment]
Looks good. Thanks!
