### ISSUE TITLE
MinHook hook of NtEnumerateKey crashes in VS2015 Win 10

### ISSUE THREAD

**Issue by juouy** [TsudaKageyu/minhook#23]
Reproduction:

* Set a hook of NtEnumerateKey of ntdll module using MH_CreateHook and MH_Enable. In MH_CreateHook use a trampoline

* Prototype of detour function looks like this:
```
NTSTATUS hookNtEnumKey(_In_      HANDLE                KeyHandle,
	_In_      ULONG                 Index,
	_In_      KEY_INFORMATION_CLASS KeyInformationClass,
	_Out_opt_ PVOID                 KeyInformation,
	_In_      ULONG                 Length,
	_Out_     PULONG                ResultLength)
{
	return tramp_nt_enum_key(KeyHandle, Index, KeyInformationClass, KeyInformation, Length, ResultLength);
}
```
* Inject DLL to Visual Studio 2015 build 14.0 x86
* Go to File->Open->Project Solution to open file browser
* App will crash just after returning from hookNtEnumKey proc - the status will be returned correctly but possibly something wrong happens on stack afterwards.

If still unable to reproduce, install Visual Assist X (i had no time to check whether this is related, imo. it's not)

**Comment by TsudaKageyu** [comment]
It looks like your prototype lacks its calling convention. How about adding ```WINAPI``` to it?

**Comment by juouy** [comment]
That was it! Thank you so much for responding.. in 15 min? :)
