### ISSUE TITLE
MH_CreateHook always return MH_ERROR_NOT_EXECUTABLE

### ISSUE THREAD

**Issue by AliAssAssInLFG** [TsudaKageyu/minhook#28]
Hi,

I just tried following code but it always return MH_ERROR_NOT_EXECUTABLE.

```C++
	LPVOID targ = GetProcAddress(LoadLibraryA("kernel32.dll"), "OpenProcess");
	MH_STATUS sts = MH_CreateHook(&targ, &hook_OpenProcess, reinterpret_cast<LPVOID*>(&hooked_OpenProcess));
	if (sts != MH_OK)
	{
		WTL(MH_StatusToString(sts));
		return 0;
	}
	
	if (MH_EnableHook(&targ) != MH_OK)
	{
		return 0;
	}
```

Used on x64 module... Following code worked fine:
```C++
	MH_STATUS sts = MH_CreateHook(&OpenProcess, &hook_OpenProcess, reinterpret_cast<LPVOID*>(&hooked_OpenProcess));
	if (sts != MH_OK)
	{
		WTL(MH_StatusToString(sts));
		return 0;
	}
	
	if (MH_EnableHook(&OpenProcess) != MH_OK)
	{
		return 0;
	}
```
But why?
Compiled with VS2015 Update 1.

**Comment by tapcio** [comment]
It can be relocation issue, I think that OpenProcess is a jmp to kernelbase.dll.

**Comment by AliAssAssInLFG** [comment]
This method worked fine in Microsoft Detours but yeah, there's jmp.

![Screenshot from OpenProcess of kernel32.dll](http://i64.tinypic.com/kb9maa.jpg)

**Comment by RaMMicHaeL** [comment]
You're passing a pointer to a pointer to the function, `&targ`.
Try the following instead:

    MH_STATUS sts = MH_CreateHook(targ, &hook_OpenProcess, reinterpret_cast<LPVOID*>(&hooked_OpenProcess));

**Comment by tapcio** [comment]
LOL, I must be blind not to see that.

**Comment by AliAssAssInLFG** [comment]
Thanks guys.
