### ISSUE TITLE
Not able to hook undocumented functions

### ISSUE THREAD

**Issue by daz3dz** [TsudaKageyu/minhook#30]
With minhook, I am not able to hook Undocumented functions. When will this be fixed?
I was trying Mhook for x64 but it is riddled with bugs (outdated) and minhook is my last option.
I've successfully hooked TerminateProcess but NtTerminateProcess isn't working.

**Comment by tapcio** [comment]
How do you hook NtTerminateProcess ? Paste your code please.

**Comment by daz3dz** [comment]
It's actually NtQuerySystemInformation but I didn't want to sound malicious. Initially I was hooking TerminateProcess and it was working but taskmgr was still able to close my app. I hooked  TerminateProcess and NtTerminateProcess. I didn't think much of it and decided to try NtQuerySystemInformation. When that wasn't working I started believing minhook can't handle undocumented functions. MH_CreateHookApi(L"ntdll", "NtQuerySystemInformation", &HookedNtQuerySystemInformation,
		(LPVOID*)&OriginalNtQuerySystemInformation) succeeds.
 MH_EnableHook(&OriginalNtQuerySystemInformation) fails and returns 1

**Comment by tapcio** [comment]
Try without using `MH_CreateHookApi`, use `LoadLibrary` or `GetModuleHandle` to get ntdll.dll handle and then use `GetProcAddress` to get original address. You can then use `MH_CreateHook` on that address.

**Comment by daz3dz** [comment]
I was initially using MH_CreateHook. I'll try it again. but can someone confirm Minhook works with undocumented functions? it's weird because I don't see a reason why it can't.

**Comment by tapcio** [comment]
Yes, it should.

**Comment by daz3dz** [comment]
MH_CreateHook fails with 1. So only MH_CreateHookApi is working for me. "Use LoadLibrary or GetModuleHandle to get ntdll.dll handle and then use GetProcAddress to get original address" is exactly what I'm doing. Can I just give you a link to my project?

**Comment by tapcio** [comment]
1 ==  MH_ERROR_ALREADY_INITIALIZED ie. is NOT fail.
I'm going to sleep now, sorry.

**Comment by daz3dz** [comment]
That's okay; thank you for taking your time to help me. Here is a link to my project for anyone to spot an error: [http://speedy.sh/U9YpK/Minhook.zip](url)

**Comment by TsudaKageyu** [comment]
```MH_EnableHook``` takes the address of ```NtQuerySystemInformation``` itself or ```MH_ALL_HOOKS```, not ```OriginalNtQuerySystemInformation```.

**Comment by daz3dz** [comment]
Thank you. Works now.
