### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by daz3dz** [TsudaKageyu/minhook#31]
Hi, this is my 2nd time here. The first time was due to not reading the changelogs and I am stupid for that (passing MH_ALL_HOOKS fixed my problem). This time my program is crashing. I am hooking TerminateProcess. I inject my dll into Taskmgr, try to terminate the protected process then
the messagebox pops up and I'm able to hit ok then the crash comes so I'm thinking it's crashing on "return 0" but I don't know why. > 1 = success and 0 = failure according to the msdn
this is my code http://pastebin.com/fR0m2AJQ

**Comment by daz3dz** [comment]
My method of injecting is the same one that I posted in my first issue.

**Comment by tapcio** [comment]
`MH_CreateHookApi(L"kernel32", "TerminateProcess", &HookedTerminateProcess, (LPVOID*)&OriginalTerminateProcess)`...
I think it should be: `MH_CreateHookApi(L"kernel32", "TerminateProcess", HookedTerminateProcess, (LPVOID*)OriginalTerminateProcess)`

**Comment by daz3dz** [comment]
Hello, I have applied your suggestions but unfortunately, taskmgr is still crashing. Btw, taskmgr also crashes whenever a new process is opened.
Also, for some reason, the MessageBoxW pops up when I try to terminate ANY process and not just the ones whose pid matches. None of this is making sense to me.

**Comment by daz3dz** [comment]
I am using winject to inject btw

**Comment by m417z** [comment]
Closing this old issue since it's probably no longer relevant. BTW, peeking at the code, you didn't specify a calling convention for `HookedTerminateProcess`, that might be the reason for the crash.
