### ISSUE TITLE
Unable to change toolset from v140_xp to v140

### ISSUE THREAD

**Issue by pisiiki** [TsudaKageyu/minhook#32]
Hello TsudaKageyu,

I'm trying to build minhook for v140 however it seems impossible to change the projects to this configuration. Target Platform and Target Platform Version in config shows blank in my VS. Please take a look at it when you can.

Regards.
Isaac Lascasas.

**Comment by Nucleoprotein** [comment]
You use correct project file form VC14 directory ?

**Comment by pisiiki** [comment]
Yeah Nucleoprotein, it is very strange. The fields for Target Platform and Target Platform Version are empty and disabled. I forgot to mention, Minhook's configured toolset defaults to v140_xp, I'm trying to build the lib myself just for v140 and sdk 8.1 because I have trouble hooking an app and I want to step into Minhook's code while debugging to see in detail what is going on.

Thanks.

**Comment by Nucleoprotein** [comment]
Quick and dirty fix - edit vcxproj in notepad (it's a xml file), and change v140_xp to v140.

**Comment by pisiiki** [comment]
Works!

Thanks.
