### ISSUE TITLE
Linux is case sensitive

### ISSUE THREAD

**Issue by G4E** [TsudaKageyu/minhook#33]
To cross compile on linux, you have to change in src/trampoline.c :
#include "./hde/hde32.h" to #include "./**HDE**/hde32.h"
and
#include "./hde/hde64.h" to #include "./**HDE**/hde64.h"

**Comment by StepS-** [comment]
I think the best solution would be to lowercase the folder, as there's really no reason for it to be uppercase. Also wouldn't require any changes to the code.

**Comment by TsudaKageyu** [comment]
I have lowercased the directory. Thanks guys!

**Comment by G4E** [comment]
It works too :)
BUT if you do that, you must change the path in build/MinGW/Makefile from
SRCS:=$(wildcard src/*.c src/HDE/*.c) to SRCS:=$(wildcard src/*.c src/**hde**/*.c)

**Comment by TsudaKageyu** [comment]
Right. Thanks again!
