### ISSUE TITLE
Windows 7 

### ISSUE THREAD

**Issue by KozmoK** [TsudaKageyu/minhook#35]
Create Hook is failing on windows 7 with MH_ERROR_MEMORY_ALLOC

Any Idea how to resolve this?  Its contained a injected DLL. It works fine on Windows 10

**Comment by Nucleoprotein** [comment]
What function you are hooking ? Maybe a code sample ?

**Comment by KozmoK** [comment]
Sorry.

This function is inside an application. I only have the offset that was returned from a signature scan.
I have tried many different ways, here is one way that works fine on windows 10

	MH_STATUS hStat = MH_CreateHook((LPVOID)gSDK->offset_DispatchMessage, &hkDispatchMessage, reinterpret_cast<void**>(&oDispatchMessage));

	if (hStat != MH_OK)
	{
		gLog->Write("Dispatch_CreateHook error - exiting aux plugin %x", hStat);
		return;
	}

	err = MH_QueueEnableHook((LPVOID)gSDK->offset_DispatchMessage);

	if (err != MH_OK)
	{
		gLog->Write("EnableHook Error for dwMessage - exiting aux plugin %x", err);
		return;
	}

	MH_ApplyQueued();


Output:  

Dispatch_CreateHook error - exiting aux plugin 9

**Comment by Nucleoprotein** [comment]
I do not think this is MinHook problem. First off - do not use offset if that code can be relocated by system, use RVA to that function - I think this is you main problem, ie gSDK->offset_DispatchMessage is pointing to wrong code on Windows 7.

**Comment by KozmoK** [comment]
I think your right, this is somehow my code issue.
This is x64 by the way.  I did not put that in my original post.

I am using a signature finder function (i.e. Pattern) that finds the function within the injected module.  Its always the same offset whether its in win 7 or win 10.  I can pull that address up in IDA and look at the code directly.

for some reason win 7 does not like me using a offset directly.

**Comment by m417z** [comment]
Closing this old issue since it's probably no longer relevant. If you were using an old version, you might have been experiencing this issue: https://github.com/TsudaKageyu/minhook/issues/10. If not, it needs more investigation.
