### ISSUE TITLE
Possible bug ? 

### ISSUE THREAD

**Issue by Karaulov** [TsudaKageyu/minhook#42]
http://i.imgur.com/Hk78Vtq.png

MinHook should do jmp after xor eax,eax ? (this is _ptr func, ppOriginal )

**Comment by RaMMicHaeL** [comment]
I could not reproduce the issue.

Before the hook:
http://i.imgur.com/cLTiHPc.png

After the hook:
http://i.imgur.com/xWVTrlK.png

The trampoline:
http://i.imgur.com/SprYmbF.png

**Comment by Karaulov** [comment]
Original function:
http://i.imgur.com/neFBJOE.png
Hooked function:
http://i.imgur.com/y2aOYjY.png
The tramp oline:
http://i.imgur.com/NMRlf00.png

**Comment by RaMMicHaeL** [comment]
I'm not familiar with Cheat Engine. I'd try a different debugger and take a look at the trampoline. You can try OllyDbg or x64dbg, both of which are free and easy to use.

**Comment by Karaulov** [comment]
Cheat Engine use Assemly language as and OllyDbg and x64dbg.

**Comment by Karaulov** [comment]
ret or jmp not needed in this function ?
http://i.imgur.com/NMRlf00.png (created by minhook)

**Comment by RaMMicHaeL** [comment]
> ?? - memory without access

Are you sure about that?
Again, please try e.g. OllyDbg. It should take no more than a couple of minutes.

**Comment by StepS-** [comment]
>Hooked function:
>http://i.imgur.com/y2aOYjY.png
>(bad! , need add NOP after JMP for make readable code)
I get what you mean by filling extra space with NOPs with cleaner code, but this is not necessary. Those parts are never executed. It would, however, improve readability in disassembly view.

**Comment by Karaulov** [comment]
http://i.imgur.com/jVAwbGh.png

yes CE problem

**Comment by RaMMicHaeL** [comment]
What's interesting is that the jump exists in the lower view.
http://i.imgur.com/zWHcVgp.png
