### ISSUE TITLE
A lot of errors running a short example

### ISSUE THREAD

**Issue by Omardavinci** [TsudaKageyu/minhook#45]
Hello i downloaded and installed minhook with nuget like you can see in the picture:
![1](https://cloud.githubusercontent.com/assets/16622854/23713365/fcf13fa6-0425-11e7-936c-39565cba1953.PNG)

Why these errors?:
![2](https://cloud.githubusercontent.com/assets/16622854/23713403/163ffdbc-0426-11e7-9aa6-6692676418e1.PNG)

i am trying to run a short example:
```
// ConsoleApplication6.cpp : définit le point d'entrée pour l'application console.
//
#include <Windows.h>
#include <MinHook.h>
#include "stdafx.h"


#if defined _M_X64
#pragma comment(lib, "libMinHook.x64.lib")
#elif defined _M_IX86
#pragma comment(lib, "libMinHook.x86.lib")
#endif

typedef int (WINAPI *MESSAGEBOXW)(HWND, LPCWSTR, LPCWSTR, UINT);

// Pointer for calling original MessageBoxW.
MESSAGEBOXW fpMessageBoxW = NULL;

// Detour function which overrides MessageBoxW.
int WINAPI DetourMessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType)
{
	return fpMessageBoxW(hWnd, L"Hooked!", lpCaption, uType);
}

int main()
{
	// Initialize MinHook.
	if (MH_Initialize() != MH_OK)
	{
		return 1;
	}

	// Create a hook for MessageBoxW, in disabled state.
	if (MH_CreateHook(&MessageBoxW, &DetourMessageBoxW,
		reinterpret_cast<LPVOID*>(&fpMessageBoxW)) != MH_OK)
	{
		return 1;
	}

	// or you can use the new helper function like this.
	//if (MH_CreateHookApiEx(
	//    L"user32", "MessageBoxW", &DetourMessageBoxW, &fpMessageBoxW) != MH_OK)
	//{
	//    return 1;
	//}

	// Enable the hook for MessageBoxW.
	if (MH_EnableHook(&MessageBoxW) != MH_OK)
	{
		return 1;
	}

	// Expected to tell "Hooked!".
	MessageBoxW(NULL, L"Not hooked...", L"MinHook Sample", MB_OK);

	// Disable the hook for MessageBoxW.
	if (MH_DisableHook(&MessageBoxW) != MH_OK)
	{
		return 1;
	}

	// Expected to tell "Not hooked...".
	MessageBoxW(NULL, L"Not hooked...", L"MinHook Sample", MB_OK);

	// Uninitialize MinHook.
	if (MH_Uninitialize() != MH_OK)
	{
		return 1;
	}

	return 0;
}
```

But show me a lot of errors?:

> Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
> Erreur	C2143	erreur de syntaxe : absence de ')' avant '*'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C2143	erreur de syntaxe : absence de ';' avant '*'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C2059	erreur de syntaxe : ')'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C2065	'HWND' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C2065	'LPCWSTR' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C2065	'UINT' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C4430	spécificateur de type manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charge int par défaut	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C2440	'initialisation' : impossible de convertir de 'initializer list' en 'int *'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	14	
> Erreur	C4430	spécificateur de type manquant - int est pris en compte par défaut. Remarque : C++ ne prend pas en charge int par défaut	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	17	
> Erreur	C2040	'MESSAGEBOXW' : les niveaux d'indirection de 'int' et de 'int *' sont différents	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	17	
> Erreur	C2146	erreur de syntaxe : absence de ';' avant l'identificateur 'fpMessageBoxW'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	17	
> Erreur	C2377	'WINAPI' : redéfinition ; un typedef ne peut pas être surchargé avec un autre symbole	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	20	
> Erreur	C2146	erreur de syntaxe : absence de ';' avant l'identificateur 'DetourMessageBoxW'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	20	
> Erreur	C2065	'HWND' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	20	
> Erreur	C2146	erreur de syntaxe : absence de ')' avant l'identificateur 'hWnd'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	20	
> Erreur	C2143	erreur de syntaxe : absence de ';' avant '{'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	21	
> Erreur	C2447	'{' : en-tête de fonction manquant (liste formelle à l'ancien format ?)	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	21	
> Erreur	C3861	'MH_Initialize' : identificateur introuvable	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	28	
> Erreur	C2065	'MH_OK' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	28	
> Erreur	C2065	'MessageBoxW' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	34	
> Erreur	C2065	'DetourMessageBoxW' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	34	
> Erreur	C2061	erreur de syntaxe : identificateur 'LPVOID'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	35	
> Erreur	C2143	erreur de syntaxe : absence de ';' avant '{'	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	36	
> Erreur	C2065	'MessageBoxW' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	48	
> Erreur	C3861	'MH_EnableHook' : identificateur introuvable	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	48	
> Erreur	C2065	'MH_OK' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	48	
> Erreur	C2065	'MB_OK' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	54	
> Erreur	C3861	'MessageBoxW' : identificateur introuvable	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	54	
> Erreur	C2065	'MessageBoxW' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	57	
> Erreur	C3861	'MH_DisableHook' : identificateur introuvable	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	57	
> Erreur	C2065	'MH_OK' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	57	
> Erreur	C2065	'MB_OK' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	63	
> Erreur	C3861	'MessageBoxW' : identificateur introuvable	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	63	
> Erreur	C3861	'MH_Uninitialize' : identificateur introuvable	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	66	
> Erreur	C2065	'MH_OK' : identificateur non déclaré	ConsoleApplication6	c:\users\androide\documents\visual studio 2015\projects\consoleapplication6\consoleapplication6\consoleapplication6.cpp	66	
>

**Comment by m417z** [comment]
Closing this old issue since it's probably no longer relevant. If you found a solution, you might want to post it to help others who might encounter the same problem.
