### ISSUE TITLE
version mingw errors undefined

### ISSUE THREAD

**Issue by Axe-Usa** [TsudaKageyu/minhook#46]
Hello i got undefined errors when i add linking files.
So The errors are:
```
C:\Users\Androide\Desktop\minhook\Dynamic>g++ -o bot.exe Dynamic.o hook.o hde32.
o buffer.o trampoline.o
hook.o:hook.c:(.text+0x60b): undefined reference to `OpenThread'
hook.o:hook.c:(.text+0x69d): undefined reference to `OpenThread'
hook.o:hook.c:(.text+0xa2c): undefined reference to `InitializeBuffer'
hook.o:hook.c:(.text+0xa7d): undefined reference to `UninitializeBuffer'
hook.o:hook.c:(.text+0xb14): undefined reference to `IsExecutableAddress'
hook.o:hook.c:(.text+0xb27): undefined reference to `IsExecutableAddress'
hook.o:hook.c:(.text+0xb52): undefined reference to `AllocateBuffer'
hook.o:hook.c:(.text+0xb7c): undefined reference to `CreateTrampolineFunction'
hook.o:hook.c:(.text+0xca0): undefined reference to `FreeBuffer'
hook.o:hook.c:(.text+0xd82): undefined reference to `FreeBuffer'
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/mingw32/4.9.2/../../../../mingw
32/bin/ld.exe: hook.o: bad reloc address 0x13c in section `.rdata'
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/mingw32/4.9.2/../../../../mingw
32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status
```
I added hook.c library to linking but return all these errors...

**Comment by Nucleoprotein** [comment]
You need to link to proper libraries, also CodeBlocks uses very old TDM-GCC 4.9.2 SJLJ (released in October 30, 2014), upgrade recommended

**Comment by Axe-Usa** [comment]
Ok i will check. Proper libraries i know but which name has for mingw. Anyways i will check with cmake and put the result.

**Comment by Nucleoprotein** [comment]
I think good start is to add "-lkernel32" to commandline.

**Comment by Axe-Usa** [comment]
yeah i added this but i anyways i get the same result, i used;
g++ -o bot.exe Dynamic.o hook.o hde32.o buffer.o trampoline.o -lkernel32

I think i must to add openthread but i dont know which is for mingw

**Comment by Nucleoprotein** [comment]
OpenThread is in libkernel32 in MinGW, try to use linker (ld.exe) to link objects or use CMake/make.

**Comment by Axe-Usa** [comment]
I send more or less a picture what i have.
![1](https://cloud.githubusercontent.com/assets/23561866/23924816/9608cc6e-090c-11e7-80cd-1e13c3630145.PNG)
![2](https://cloud.githubusercontent.com/assets/23561866/23924937/1d7e2d4c-090d-11e7-86c8-d63e866bed6a.PNG)
i think i must to use makefiles. So i think i must first make the make file and then compile with cmake?

**Comment by Axe-Usa** [comment]
If not say me how i must to use ld.exe? i put:
g++ -o bot.exe Dynamic.o hook.o hde32.o buffer.o trampoline.o -lkernel32

But ld.exe i can't use it anyways thanks for your help really useful i will try still

**Comment by Axe-Usa** [comment]
with ld i tried and return me:
```
C:\Users\Androide\Desktop\minhook\Dynamic>ld -o bot.exe Dynamic.o hook.o
Dynamic.o:Dynamic.cpp:(.text+0x43): undefined reference to `__main'
Dynamic.o:Dynamic.cpp:(.text+0x99): undefined reference to `MessageBoxW@16'
Dynamic.o:Dynamic.cpp:(.text+0xd8): undefined reference to `MessageBoxW@16'
Dynamic.o:Dynamic.cpp:(.text+0xe2): undefined reference to `MessageBoxW@16'
Dynamic.o:Dynamic.cpp:(.text+0x11e): undefined reference to `MessageBoxW@16'
ld: Dynamic.o: bad reloc address 0x22 in section `.text$_Z18MH_CreateHookApiExI
iP6HWND__PKwS3_jEE9MH_STATUSS3_PKcPvPPT_[__Z18MH_CreateHookApiExIFiP6HWND__PKwS
_jEE9MH_STATUSS3_PKcPvPPT_]'
ld: final link failed: Invalid operation
```
With cmake i didnt check it but the same result.

**Comment by Axe-Usa** [comment]
I dont know but i will try to use msys. Not a lot of tutorial in internet.

**Comment by Axe-Usa** [comment]
i am installing i will share you my experiencie soon.
![msys](https://cloud.githubusercontent.com/assets/23561866/23931249/92b891a0-0931-11e7-85bf-97494f784a2e.PNG)

**Comment by Axe-Usa** [comment]
I get the same errors with msys:
![errors](https://cloud.githubusercontent.com/assets/23561866/23931646/581df998-0933-11e7-8185-4fb02ebf6726.PNG)

**Comment by Nucleoprotein** [comment]
Hym, `-shared` ?

**Comment by Axe-Usa** [comment]
Yeah i did all well i installed using:
`pacman --noconfirm -Suy python2 make pkg-config mingw-w64-i686-glib2 mingw-w64-i686-toolchain mingw-w64-i686-gcc    ` 

And running return me these errors again. If you can say how will be with make command i can try it and share my experience.

**Comment by Axe-Usa** [comment]
Anyways when i compile hook.c show me:
```
C:\Users\Androide\Desktop\minhook-master\build\MinGW>windres -i ../../dll_reso
ces/MinHook.rc -o MinHook_rc.o   && dllwrap --driver-name g++ -o MinHook.dll -
sm=intel --def ../../dll_resources/MinHook.def -Wl,-enable-stdcall-fixup -Wall
inHook_rc.o ../../src/*.c ../../src/HDE/*.c -I../../include -I../../src -Werro
-std=c++11 -s -static-libgcc -static-libstdc++  || pause
../../src/hook.c: In function 'void Freeze(PFROZEN_THREADS, UINT, UINT)':
../../src/hook.c:319:82: error: 'OpenThread' was not declared in this scope
             HANDLE hThread = OpenThread(THREAD_ACCESS, FALSE, pThreads->pItem
i]);

  ^
../../src/hook.c: In function 'void Unfreeze(PFROZEN_THREADS)':
../../src/hook.c:338:82: error: 'OpenThread' was not declared in this scope
             HANDLE hThread = OpenThread(THREAD_ACCESS, FALSE, pThreads->pItem
i]);

  ^
dllwrap: g++ exited with status 1

```
But i get the hook.c i think this is the problem hook.c

**Comment by Axe-Usa** [comment]
I compiled all again and dont work..
![1](https://cloud.githubusercontent.com/assets/23561866/23951682/2d524802-098f-11e7-9cc3-404298b8ae8c.PNG)
Dont work

**Comment by Axe-Usa** [comment]
Open thread error dissapear still other errors show me:
![aaa](https://cloud.githubusercontent.com/assets/23561866/23951831/b6ad62b2-098f-11e7-9206-82232d13a108.PNG)

**Comment by Axe-Usa** [comment]
how i can link buffer correctely:
g++ -o /c/Users/Androide/Desktop/minhook/Dynamic/bot.exe /c/Users/Androide/Desktop/minhook/Dynamic/Dynamic.o -L/c/Users/Androide/Desktop/minhook/Dynamic/ -lbuffer

C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lbuffer
collect2.exe: error: ld returned 1 exit status

**Comment by Axe-Usa** [comment]
Hello friend how i can link buffer..:
![avala](https://cloud.githubusercontent.com/assets/23561866/23957540/ea8e1e5e-099f-11e7-9580-90fb0f6cf72d.PNG)

**Comment by Axe-Usa** [comment]
Hello????

**Comment by Nucleoprotein** [comment]
I think this issue should be closed - it's a problem with user build 'system', not MinHook.

@Axe-Usa 
Please learn how to use GCC/Make/CMake ect. this not place to ask for such things.

**Comment by Axe-Usa** [comment]
i think will be good explain to the new users want to use this library how to use it.. in mingw or windows but like you think this i close the thread.

**Comment by Nucleoprotein** [comment]
Like all other libraries, you should compile library separately and link to it your program, Makefile for MinGW is included in build/MinGW, I dunno why you want to link MinHook to your app directly ...

**Comment by Axe-Usa** [comment]
Thanks for your help worked i did this:
g++ -o bot.exe Dynamic.o hook.o -L/c/Users/Androide/Desktop/minhook/Dynamic/ trampoline.a buffer.a hde32.a

Wait other people is useful or help! thx Nucleoprotein you are i was wrong the library works so fine.

**Comment by Nucleoprotein** [comment]
I was thinking more about `make -f build/MinGW/Makefile` in main minhook directory - this will create few files: libMinHook.a - static library, libMinHook.dll.a and MinHook.dll - shared library. I recommend to link to static library ie libMinHook.a
