### ISSUE TITLE
Possible to speedup minhook ?

### ISSUE THREAD

**Issue by Karaulov** [TsudaKageyu/minhook#55]
I need create 17689 hooks. I wait 5 minutes... But hooks still no created.

**Comment by RaMMicHaeL** [comment]
Don't call `MH_EnableHook` for every hook. Instead, call `MH_EnableHook(MH_ALL_HOOKS)` after creating all of your hooks.
See [this comment](https://www.codeproject.com/Messages/4560980/Re-Performance-Issue-for-Large-sharp-of-Hooks.aspx).

**Comment by Karaulov** [comment]
OK.
