### ISSUE TITLE
Hook works at startup, but stop working soon

### ISSUE THREAD

**Issue by altexy** [TsudaKageyu/minhook#56]
Hi

I inject my DLL into a process using AppInit_DLLs registry key.
I use GetModuleFileNameW() and hardcoded process name to ignore others processes.

In minimal test I successfully hook CloseHandle() function.

```

typedef BOOL(WINAPI *CLOSE_HANDLE)(HANDLE);
CLOSE_HANDLE CloseHandleTrampoline = CloseHandle;
BOOL WINAPI CloseHandleHooked(
	_In_ HANDLE hObject
)
{
	LONG c = InterlockedIncrement(&counter);
        Log(L"CloseHandle counter: %d\n", (int)counter);
	return CloseHandleTrampoline(hObject);
}

...
void HookInit()
{
       // checking process names
       ...

	if (MH_Initialize() != MH_OK)
	{
		Log(L"MH_Initialize() fails\n");
		return;
	}
	if (MH_CreateHookApiEx(L"kernel32", "CloseHandle", &CloseHandleHooked, &CloseHandleTrampoline) != MH_OK)
            
	{
		Log(L"MH_CreateHookApiEx() fails for CloseHandle\n");
	}
	if (MH_EnableHook(MH_ALL_HOOKS) != MH_OK)
	{
		Log(L"MH_EnableHook(MH_ALL_HOOKS) fail\n");
	}
       Log(L"32 bit process hooked [%lu]\n",  GetCurrentProcessId());
}
```
My Log() function just open a file, write and close, uses CloseHandleTrampoline() to avoid infinity recursion.

When I start my process I see some CloseHandle() logs but after a second I don't see such logs and I'm sure that my test and production programs do call CloseHandle() during this time .

The hook DLL is still loading in address space of my process, but the behaviour looks like original state of kernel21.dll was restored.
I can repeat on 2 different computes:
- Windows 8.1 desktop - my home dev PC
- Windows Server 2008 R2 Enterprise - test server in the cloud

Does somebody have an idea or any clue how to debug/solve this problem?

**Comment by RaMMicHaeL** [comment]
Use a low-level assembly debugger, such as OllyDbg (32-bit) or x64dbg:
1. Break on `MH_EnableHook`.
2. Go to `CloseHandle`, and notice that the first command is not a jump.
3. Step over the `MH_EnableHook` call.
4. Go to `CloseHandle` again, and notice that the first command was overwritten with a jump.
5. Right click on the jump command, and set a hardware breakpoint on write.
6. Resume your process. If the hook will be removed, the breakpoint will be triggered, and you can see in the stack trace where it comes from.

**Comment by altexy** [comment]
@RaMMicHaeL  thanks!
