### ISSUE TITLE
Hi, is it possible, to hook processes, created through CreateProcess ?

### ISSUE THREAD

**Issue by effolkronium** [TsudaKageyu/minhook#57]
Can u give a sample if it's possible?

**Comment by RaMMicHaeL** [comment]
You'll have to run your code in the context of the target process.
MinHook doesn't provide a way to do that, you'll have to do it yourself.
There are several techniques for this, here's an example for one of them:
https://github.com/RaMMicHaeL/winspy/blob/master/src/InjectThread.c

**Comment by effolkronium** [comment]
Thanks, i'll take a look
