### ISSUE TITLE
call function instead of jumping to it?

### ISSUE THREAD

**Issue by Keptark** [TsudaKageyu/minhook#61]
Why can I only do a jump to the `*ppOriginal` address returned `MH_CreateHook()`? Doing a call from C++ or assembly does not work, for some reason I have to use a `jmp` instruction for it to work...?

**Comment by Kaldaien** [comment]
Because that's the address of the relocated instructions. You need to call the "trampoline" function, whose purpose it is to jump there.

**Comment by Keptark** [comment]
But ppOriginal is exactly that, it's described as: "[Out] A pointer to the trampoline function, which will be used to call the original target function"

But the function I hook with is an assembly function, where inside i execute the "call trampolineFunction". It always end up crashing though, so I must be calling it in a wrong way. And this is in x64.
