### ISSUE TITLE
hook free in debug mode failed

### ISSUE THREAD

**Issue by UhlanZW** [TsudaKageyu/minhook#71]
I try to hook "malloc" and "free" in my project. However, I find that "free" can only be hooked in release mode, while "malloc" can be hooked in bose debug and release mode. Here is my code:

```
#include "MinHook.h"
#include<iostream>
typedef void * (__cdecl *PtrMalloc)(size_t);
typedef void(__cdecl *PtrFree)(void *);





PtrMalloc orgi_malloc;
PtrFree orgi_free;
int inter_a, inter_b;
void *my_malloc(size_t size)
{
	inter_a++;
	return orgi_malloc(size);
}

void my_free(void*p)
{
	inter_b++;
	orgi_free(p);
	return;
}



int main()
{
	MH_Initialize();
	MH_CreateHook(&malloc, my_malloc, (void**)&orgi_malloc);
	MH_CreateHook(&free, my_free, (void**)&orgi_free);
	MH_EnableHook(&free);
	MH_EnableHook(&malloc);
	int *a = new int[1000];
	delete[]a;
	a = new int[100];
	delete[]a;
	inter_a;
	inter_b;
	return 0;
}
```

I wish you can help me, thank you!

**Comment by Nucleoprotein** [comment]
I think there is a different free in debug CRT and have some incompatibility with hooking.
Why you test this code using `new` operator? CRT my or may not use malloc/free internally - it's up to C++ runtime decision how to do stuff there.
Also what with all those empty `#include` ??????

**Comment by UhlanZW** [comment]
1.I have tried to hook "HeapAlloc" and "HeapFree". The result is the same: any malloc or new can enter my defined "malloc" but free can not enter my defined "free", could you tell me which functions should be hooked to monitor the "free" function in debug mode? I have not founded yet.
2.I want to profile memory allocations in my project, and I think "new" and "delete" call "malloc" and "free" as well, so I try to hook "malloc" and "free" only. In fact, whenever "new" is called, defined "malloc" is also called.
3. It is "#include<iostream>", and it doesn't display correctly.
Thank you!

**Comment by RaMMicHaeL** [comment]
`delete` might not use `HeapFree` internally. In any case, looks like MinHook is an overkill for your task. You can just [overload `new` and `delete` in C++](https://www.geeksforgeeks.org/overloading-new-delete-operator-c/).

**Comment by UhlanZW** [comment]
Thanks a lot.
However, I want to monitor every allocations in my project. Override "new" and "delete" can not hook memory allocations in dll or system libraries, for example "strdup", so maybe I need function hooks.

**Comment by UhlanZW** [comment]
Thank you all. I have fixed this problem by hooking _free_dbg function, in this way, I can monitor the memory dealloations in debug mode.
