### ISSUE TITLE
It doesn't work  with IIS/Asp.Net/Web application. How we can do this???

### ISSUE THREAD

**Issue by Ashutosh-K-Singh** [TsudaKageyu/minhook#76]
I have tried with Asp.net web application hosted in IIS server. After many attempt i couldn't succeed .Is there any way to do that?

**Comment by mrsshr** [comment]
Describe what you tried, expected results, and actual results.

**Comment by Ashutosh-K-Singh** [comment]
Does Minhook provides any mechanism to hook .net web applications?

**Comment by BigJim** [comment]
> Does Minhook provides any mechanism to hook .net web applications?
You need to learn enough Windows internals on how API code hooks work.
Beyond the scope of a simple answer here.
You might want to hook .NET CIL byte code for which this library won't work, it's for x86-64 machine code.
Web search, start reading..

**Comment by lambwheit** [comment]
you can hook the win32 apis that the .net program will eventually call and it will work

**Comment by m417z** [comment]
Looks like the question was answered.
