### ISSUE TITLE
Question about multihooking

### ISSUE THREAD

**Issue by ryobg** [TsudaKageyu/minhook#78]
Hello,

my knowledge is not sufficient enough to understand the intrinsics of the library itself, but I want to provide something like multiple hooking support. I'm aware that there is a fork doing that for the price of few features, but reading across the internet I started to believe that if the control is in  single hands it may be possible to reorder properly the hooks. Hence, my question is does the proper chain of first-in, last-out has to be kept with regard the creation of a hook, or only for enable/disable? Or for both? Or not possible at all in this repo?

Thank you!

**Comment by m417z** [comment]
> does the proper chain of first-in, last-out has to be kept with regard the creation of a hook, or only for enable/disable? Or for both?

Both. When a hook is created, a so-called "trampoline" is being built. The trampoline re-creates the first command(s) of the target function in a different location. See [this image](http://www.malwaretech.com/wp-content/uploads/2015/01/CodeFlow.png) for an illustration.

One of the assumptions of the library is that the target function never changes, so the trampoline is built only once. It so happens that creating another hook for the target function creates a chain of hooks, and it works, but only as long as the order is first-in, last-out. (and it probably won't work for the short version of the hook, when the function is short and the jump is placed above it, [like this](https://i.imgur.com/fE25QTa.png))

**Comment by ryobg** [comment]
Hi @m417z !

thank you very much for your answer. It confirms what I had suspected. "Create" makes a snapshot of the target and "enable" just places the jump. So the last hook, will call the previous and so on (that is if the hook calls the original). This also means that you can't pop a hook in the middle without unwinding the stack so to say. Well, maybe it is not so bad, but I will think a bit more. It won't be an issue to manage these operations because the application I'm thinking off will manage the order of the hooks and their create/enabled state behind the scenes.

Thank you again!
