### ISSUE TITLE
Question about disabling hook

### ISSUE THREAD

**Issue by zonya1** [TsudaKageyu/minhook#90]
I need to disable a hook after a certain function has been called, inside the hooked code. So far I have just called MH_DisableHook inside the hook function and there does not seem to be any issues yet but I was wondering if this is a safe way to do it? Should you call it outside the hooked code to ensure there is no crash or other issues, or is this fine?

**Comment by Nucleoprotein** [comment]
I think MH_DisableHook only changes a pointer in trampoline to point to original function so it should be safe.

**Comment by m417z** [comment]
`MH_DisableHook` just [restores the bytes at the beginning on the function](https://github.com/TsudaKageyu/minhook/blob/4a455528f61b5a375b1f9d44e7d296d47f18bb18/src/hook.c#L408-L411), so as @Nucleoprotein said, it's completely safe to call it inside the hooked function.
