### ISSUE TITLE
Question about possibily use of minhook in "ReadOnly" mode

### ISSUE THREAD

**Issue by luca2125** [TsudaKageyu/minhook#91]
Hi,

Sometimes when I use IDA I need to read the paramenters of some function.

In some cases there are __usercall functions  that are very hard to manage.

I ask if is possible access to a function paramenters only without need create a line like: 

Return origAddress(.....);

at the end of the detour function

To do an example of what I like to ask:

```
bool ReadOnly = true;
MH_CreateHook(origAddress, hookFunction, ReadOnly);
```

I ask if hookFunction before finish can call automatically "origAddress" before end of function.

So I can read all parameters of the function without worrying about how to call the original function.

In case of __usercall functions is not always easy create a assembly code that call the original function.

There is a way to do it ? or other alternatives ?

Thanks !

**Comment by m417z** [comment]
You can implement `hookFunction` such that you don't call `origAddress`, but jump to it. For example:

```assembly
hookFunction:
    ; pre-process what's needed
    jmp origAddress
```

You can also modify the registers and the stack, there's nothing "read only" about it really. The main limitations of this approach are:
* You have to use assembly.
* You can't change the return value or run code after the hooked function returns.

You can also check out this project: https://github.com/vovkos/protolesshooks
I haven't tried it myself, but from the description it looks like it's designed to do what you're looking for.

**Comment by luca2125** [comment]
many thanks for reply !!

I see that with:

jmp origAddress

my original function work perfecly without side effect.

There is only a problem:

because I use naked function with __usercall I can't add my c++ code and If I call my code to another function lose the parameters stack indepent by the code inside (just declare a string to do an example).

Do you think there is a way to bypass this problem ?

Thanks !

**Comment by m417z** [comment]
My guess would be that by issuing a function call, you stomp over registers which are assumed to be preserved by the custom calling convention. You can save those registers, and restore them after the call. In 32-bit x86 there're the PUSHAD/POPAD instructions which help saving all registers. for x86-64, you'd have to push the required registers one by one.

**Comment by luca2125** [comment]
You have right another time.

Now all work perfectly !!!

Thanks !!

Please leave me a coriosity:

pushad: Do a backup of a current state of all registry, and popad restore the previous backup,

Is correct ?

**Comment by m417z** [comment]
Correct. There are also the PUSHF/POPF instructions to save and restore the CPU flags. Those are still available in x86-64.

**Comment by luca2125** [comment]
Hi m417z,

Please excuse me for disturb.

With your last very good suggest now I have hooked many __usercall functions without problems.

But sometimes I need to hook a __userpurge functions and seem different. For example I have tried to hook this:

// int __userpurge sub_6407AE@<eax>(_DWORD *a1@<ecx>, int a2@<ebp>, int a3@<edi>, int a4@<esi>, _OWORD *a5, int a6)
__declspec(naked) int __stdcall HookDamageSub_BZCC(DWORD * ecx, int ebp, int edi, int a4, DWORD *a5, int a6)
{
	__asm
	{
		popad
		jmp AddressOfHookDamageFunction
	}
}

but crash probably becouse is not the right way to hook a __userpurge. Have you some suggest ?

Thanks at advance !

**Comment by m417z** [comment]
According to [this](https://stackoverflow.com/questions/6844019/how-to-hook-convert-userpurge-func-to-stdcall-or-cdecl), `__userpurge` is the same as `__usercall`, except the callee cleans up the stack. It shouldn't make a difference in your case, since the return from the function is done by the original function.

In your snippet, why did you use `popad` without `pushad`? What if you just use `jmp`, does it crash?

**Comment by luca2125** [comment]
You have right as usual ...

Apart this that probably can be cause of the crash, I need probably replace  "_OWORD" with long long.

Many many thanks !!!!

**Comment by luca2125** [comment]
Hi m417z,

You have right I still disturb you too much times please excuce me again.

I have another problem:

I need to declare a naked function on header file:

 __declspec(naked) void HookSoundFileSub_BZCC_Asm(char  *Src, int pedx, int a3, int a4, int a5, int a6);
 __declspec(naked) void __stdcall HookDamageSub_BZCC_Asm(DWORD * ecx, int ebp, int edi, int a4, long long *a5, int a6);

and I get this error (C2488) 'identifier' : 'naked' can only be applied to non-member function definitions.

Have you a suggest ?

Many thanks again !!

**Comment by m417z** [comment]
Are those member functions? If so, perhaps marking them as static will
help.

If not, please post a whole snippet that triggers this error message.

**Comment by luca2125** [comment]
Thank you for your fast response :)

These functions are not member of class but are only public function and with "static" the problem is not solved:

In short I have a header file:;

// These rows generate the compite error (C2488)  
 //__declspec(naked) void HookSoundFileSub_BZCC_Asm(char  *Src, int pedx, int a3, int a4, int a5, int a6);
 //__declspec(naked) void __stdcall HookDamageSub_BZCC_Asm(DWORD * ecx, int ebp, int edi, int a4, long long *a5, int a6);

// these rows don't generate any compile errors but when the functions are called crash
 void HookSoundFileSub_BZCC_Asm(char  *Src, int pedx, int a3, int a4, int a5, int a6);
 void __stdcall HookDamageSub_BZCC_Asm(DWORD * ecx, int ebp, int edi, int a4, long long *a5, int a6);

to solve the problem I can use these function inside the main without declare the prototype, but if possible I like to declare it inside another c++ module.

**Comment by m417z** [comment]
According to [this](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2488?view=msvc-160), you need to add `__declspec(naked)` to the definition, not the declaration.
