### ISSUE TITLE
visual studio 2019 Cannot be used

### ISSUE THREAD

**Issue by EricYoung121** [TsudaKageyu/minhook#93]
Using visual studio 2019 to prompt me that I can't parse the external commands of MinHook, what should I do?

**Comment by lambwheit** [comment]
show error?

**Comment by EricYoung121** [comment]
> 显示错误？

The problem has been solved.

**Comment by Natrox** [comment]
Hello,

For the sake of others who encounter this error in the future, would you kindly  explain how you solved the issue?

Thanks,
Sam

**Comment by EricYoung121** [comment]
> 你好,
> 
> 为了将来遇到这个错误的其他人，你能解释一下你是如何解决这个问题的吗？
> 
> 谢谢,
> 萨姆

Yes, of course. 
At first, the static link library did not load successfully, because I added the library path to debug, and compiled using release, so the library could not be loaded correctly. 
Just reset the path.

**Comment by Natrox** [comment]
Ah, I understand.
