### ISSUE TITLE
Does MinHook support hooking the same address twice?

### ISSUE THREAD

**Issue by matcool** [TsudaKageyu/minhook#94]
I have two DLLs that both dynamic link MinHook and hook the same address in a game, however, only one of the DLLs gets their hook placed, while the other gets the error `MH_ERROR_ALREADY_CREATED`
Is there some way to make it so both hooks work?

**Comment by m417z** [comment]
It's not supported by MinHook, but you can check out my extension that can be found under the [multihook branch](https://github.com/m417z/minhook/tree/multihook). It allows to hook the same function multiple times by attaching an identity to each hook, for example:

```
MH_CreateHookEx(1, &MessageBoxW, &DetourMessageBoxW1, &fpMessageBoxW1);
MH_CreateHookEx(2, &MessageBoxW, &DetourMessageBoxW2, &fpMessageBoxW2);
```

**Comment by matcool** [comment]
Thanks! Everything seems to work except for DisableHook, which crashes here for some reason
![image](https://user-images.githubusercontent.com/26722564/120084125-37e73180-c0a4-11eb-8872-4ff8140cd16a.png)

**Comment by m417z** [comment]
Can you provide a minimal project that reproduces the problem?

**Comment by matcool** [comment]
After some poking around, it seems to come from the fact that the same function was being hooked by another DLL which uses a completely different hooking library. The conflict comes from, what i assume, dealing with different instances of minhook hooking the same function.
What I ended up doing instead is chaining hooks myself, by hooking the trampoline function of the previous hook
